# P3 (Управління майном, приватизація, сприяння розвитку підприємництва та здійснення державної регуляторної політики): 2/2

In [1]:
import pandas as pd
from src.utils import normalize_parameter, save_data
from src.utils import PATH_INTERIM

---

## p3_01
### оголошена вартість майна, що реалізується в рамках малої приватизації у регіоні протягом звітного періоду
## p3_02
### дохід від малої приватизації у регіоні протягом звітного періоду

In [2]:
df_P03_005 = pd.read_excel(PATH_INTERIM / "P3" / "P03_005.xlsx")
df_P03_005['Місто організатора'] = df_P03_005['Місто організатора'].fillna('невідомо')
df_P03_005.loc[df_P03_005['Місто організатора'].str.contains(r'Ки[еї]в'),'Регіон організатора'] = 'м. Київ'

df_P03_005_fin = df_P03_005.groupby('Регіон організатора', as_index=False).agg({'Оголошена вартість':'sum','Дохід':'sum'})
df_P03_005_fin = df_P03_005_fin.loc[~df_P03_005_fin["Регіон організатора"].isin(['м. Київ', '-'])]
df_P03_005_fin = df_P03_005_fin.reset_index().rename(columns={'Регіон організатора':'region'})
df_P03_005_fin = df_P03_005_fin.rename(columns={'Оголошена вартість':'p3_01_raw','Дохід':'p3_02_raw'})

df_P03_005_fin["p3_01"] = normalize_parameter(df_P03_005_fin["p3_01_raw"])
df_P03_005_fin["p3_02"] = normalize_parameter(df_P03_005_fin["p3_02_raw"])

feature_range=(0, 1); fill_na=True; array_bounds=(149689.22, 428885075.78); normalization_bounds=(149689.22, 428885075.78)
feature_range=(0, 1); fill_na=True; array_bounds=(342983.0, 1119649422.52); normalization_bounds=(342983.0, 1119649422.52)

## Група 1: p3_01-p3_02, обсяги малої приватизації

In [3]:
dict_weights = {
    'p3_01':1,
    'p3_02':1,
}

sources = [df_P03_005_fin]
save_data(sources, dict_weights, 'P3', show_results=True)

               region     p3_01     p3_02         P3
0           Вінницька  0.164924  0.012149   0.885364
1           Волинська  0.004086  0.001251   0.026684
2    Дніпропетровська  0.083389  0.016696   0.500427
3            Донецька  0.050861  0.001310   0.260856
4         Житомирська  0.004024  0.003415   0.037195
5        Закарпатська  0.042318  0.006760   0.245390
6          Запорізька  0.015598  0.002596   0.090970
7   Івано-Франківська  0.096351  0.011693   0.540220
8            Київська  1.000000  1.000000  10.000000
9      Кіровоградська  0.006929  0.000000   0.034644
10          Луганська  0.000000  0.000612   0.003059
11          Львівська  0.494401  0.097212   2.958063
12       Миколаївська       NaN       NaN        NaN
13            Одеська  0.074322  0.008095   0.412083
14         Полтавська  0.076490  0.004429   0.404596
15         Рівненська  0.084568  0.003209   0.438888
16            Сумська  0.013471  0.001357   0.074142
17      Тернопільська  0.006477  0.002271   0.043739
18         Харківська  0.089596  0.012719   0.511578
19         Херсонська  0.089966  0.033571   0.617684
20        Хмельницька  0.055399  0.003580   0.294897
21          Черкаська  0.046024  0.006459   0.262415
22        Чернівецька  0.019722  0.032083   0.259024
23       Чернігівська  0.037927  0.004343   0.211349
24             м.Київ       NaN       NaN        NaN